//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
namespace CredentialManagementPortal
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTotalCount;
        protected global::System.Web.UI.WebControls.Label lblVpnCount;
        protected global::System.Web.UI.WebControls.Label lblAxCount;
        protected global::System.Web.UI.WebControls.Label lblEmailCount;
        protected global::System.Web.UI.WebControls.Label lblUserCount;
        protected global::System.Web.UI.WebControls.Label lblProductKeyCount;
        protected global::System.Web.UI.WebControls.Label lblDomainCount;
        protected global::System.Web.UI.WebControls.Label lblSslCount;
        protected global::System.Web.UI.WebControls.Label lblCurrentUserName;
        protected global::System.Web.UI.WebControls.Label lblCurrentUserRole;
        protected global::System.Web.UI.WebControls.Label lblAvatarInitial;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Repeater rptRecentActivity;
        protected global::System.Web.UI.WebControls.Panel pnlNoRecentActivity;
        protected global::System.Web.UI.WebControls.Repeater rptExpiringSoon;
        protected global::System.Web.UI.WebControls.Label lblExpiringEmpty;
    }
}







