//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
namespace CredentialManagementPortal
{
    public partial class DomainAndSSL
    {
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;
        protected global::System.Web.UI.WebControls.Button btnAddDomain;
        protected global::System.Web.UI.WebControls.GridView gvDomains;
        protected global::System.Web.UI.WebControls.Button btnAddSsl;
        protected global::System.Web.UI.WebControls.GridView gvSsl;
        protected global::System.Web.UI.WebControls.HiddenField hfDomainID;
        protected global::System.Web.UI.WebControls.TextBox txtDomainName;
        protected global::System.Web.UI.WebControls.TextBox txtRegistrar;
        protected global::System.Web.UI.WebControls.TextBox txtDNS;
        protected global::System.Web.UI.WebControls.TextBox txtDomainExpiry;
        protected global::System.Web.UI.WebControls.Button btnSaveDomain;
        protected global::System.Web.UI.WebControls.HiddenField hfSslID;
        protected global::System.Web.UI.WebControls.TextBox txtSslProvider;
        protected global::System.Web.UI.WebControls.TextBox txtCertificateType;
        protected global::System.Web.UI.WebControls.TextBox txtSslExpiry;
        protected global::System.Web.UI.WebControls.Button btnSaveSsl;
    }
}
