//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CredentialManagementPortal
{
    public partial class ProductKeys
    {
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.GridView gvProductKeys;
        protected global::System.Web.UI.WebControls.HiddenField hfID;
        protected global::System.Web.UI.WebControls.TextBox txtSoftware;
        protected global::System.Web.UI.WebControls.TextBox txtVersion;
        protected global::System.Web.UI.WebControls.TextBox txtProductKey;
        protected global::System.Web.UI.WebControls.TextBox txtLicenseType;
        protected global::System.Web.UI.WebControls.TextBox txtAssignedTo;
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
