//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
namespace CredentialManagementPortal
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.PlaceHolder phAppSidebar;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDashboard;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navVpn;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navAx;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navEmail;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navProductKeys;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navDomainSsl;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}


